frontend/src/app/layout.tsx
frontend/src/app/page.tsx
frontend/src/features/directory/api/fetchVendors.ts
frontend/src/features/directory/components/Directory.tsx
frontend/src/features/directory/components/FilterableVendorTable.tsx
frontend/src/features/directory/components/VendorCard.tsx
frontend/src/features/directory/components/VendorGrid.tsx
frontend/src/types/supabase.ts
frontend/src/types/vendor.ts

- add types from supabase
- prefetch all vendors and cache them using next.js unstable_cache
- display vendors based on scrolling
- remove nested scroll box

Add infinite scroll and prefetch all vendors

---

frontend/package.json
frontend/src/components/security/ReCaptcha.tsx
frontend/src/features/recommendations/api/createRecommendation.ts
frontend/src/features/recommendations/components/RecommendationForm.tsx
frontend/src/lib/security/recaptchaVerification.ts

* separate recaptcha keys for dev and prod, so that prod doesn't get polluted with tests. Prod keys are on vercel, dev keys are on bitwarden

Add recaptcha 

---

frontend/.gitignore
frontend/src/features/admin/api/createVendor.ts
frontend/src/features/admin/components/VendorManagement.tsx
frontend/src/lib/hubspot/hubspot.ts

* create a new contact hubspot when new vendors are added through the admin form
* add toast to the admin form for better messaging

set up hubspot integration with admin management

---

frontend/src/components/layouts/Footer.tsx
frontend/src/components/ui/KoFiButton.tsx

Add buy us a coffee button using Ko-Fi link

Add buy us a coffee button to the footer ![](https://files.slack.com/files-pri/T06UT6MG134-F08NCNSPSH5/screenshot_2025-04-18_at_1.03.37___pm.png)

---

frontend/src/app/layout.tsx
frontend/src/components/ui/FeatureCTABanner.tsx

Open to other color ideas!
light mode:
dark mode:

Add banner for new feature

---

frontend/src/features/directory/components/VendorCard.tsx
frontend/src/features/directory/components/VendorGrid.tsx

add card position metrics to show the impact of being in a higher position

add card position metrics

---

frontend/package.json
frontend/src/features/directory/components/FilterableVendorTable.tsx
frontend/src/features/directory/components/LocationFilter.tsx
frontend/src/features/directory/components/SearchBar.tsx
frontend/src/features/directory/components/SkillFilter.tsx
frontend/src/features/directory/components/TravelFilter.tsx
frontend/src/features/directory/components/VendorCard.tsx
frontend/src/utils/analytics/trackFilterEvents.ts

* Add event for filter change
* Add event for search terms
* Add event for when filters and search terms are applied, with info about number of results
* Debounce the search to improve perf and limit events sent
* Fix scrolling when typing so window stays in the same place
* tested by setting up GTM and testing against the preview deployment

Add events for filters and search

---

frontend/package.json
frontend/src/app/blog/[slug]/page.tsx
frontend/src/app/layout.tsx
frontend/src/components/analytics/Analytics.tsx
frontend/src/components/layouts/Navbar.tsx
frontend/src/components/ui/ContentfulImage.tsx
frontend/src/components/ui/RichText.tsx
frontend/src/features/blog/components/Article.tsx
frontend/src/features/blog/components/ArticleTable.tsx
frontend/src/lib/constants.ts
frontend/src/lib/env/env.ts
frontend/src/lib/security/recaptchaVerification.ts

* integrate Vercel development/preview/production environmental variables with Node development/production environmental variables
* configure analytics for prod environments only, with flags to override
*  Allow future blogs to be seen in development and preview environments

Add env controls for dev/preview

---

frontend/src/features/directory/components/FilterableVendorTable.tsx
frontend/src/types/sort.ts

* Use default option when location isn't selected
* When location is selected, automatically select "distance" option
* small refactor to make sort options into constants

Add a default sort option

---

frontend/src/types/vendor.ts

Use a prefix that works for public and signed links

relax image prefix

---

frontend/src/app/layout.tsx
frontend/src/app/vendors/[slug]/page.tsx
frontend/src/components/layouts/LocationBreadcrumbs.tsx
frontend/src/features/business/components/VendorDetails.tsx
frontend/src/lib/location/locationNames.ts
frontend/src/lib/location/locationSlugs.ts

Add location breadbrumbs to vendor pages

---

frontend/src/features/business/components/VendorDetails.tsx

Add testimonial and photo count to profile_view_duration event

add premium metrics

---

frontend/src/features/directory/components/FilterableVendorTable.tsx
frontend/src/features/directory/components/VendorCard.tsx

* Don't add a trailing ? to vendor url if there are no params
* Memoize and reuse search param string
* Fix bug with sort object by using the name as the value
Location and Sort are not included as search params. I'll add them in a separate PR.

fix url for vendors when there are no params

---

frontend/src/components/layouts/PhotoCarousel.tsx
frontend/src/components/layouts/SwiperCarousel.tsx
frontend/src/features/business/components/VendorDetails.tsx
frontend/src/features/directory/components/VendorCard.tsx

* add metrics for the photo carousel
* Refactor card click event to work with photo carousel arrows

add photo carousel metrics

---

frontend/src/features/directory/api/searchVendors.ts
frontend/src/features/directory/components/FilterableVendorTable.tsx
frontend/src/lib/location/LocationPageGenerator.ts
frontend/src/types/supabase.ts

* This uses a new RPC for getting vendors by location and returning the premium photos
* Also prioritize premium cards for location pages using the automatic sort (which is by distance)
To do:
I haven't updated the sql migration file because the supabase CLI needs updating, which requires Command Line Tools to be updated

Update RPC for premium vendor media

---

frontend/src/components/theme/themePrimitives.ts
frontend/src/components/ui/FilterChip.tsx
frontend/src/features/business/components/VendorDetails.tsx
frontend/src/features/directory/components/Directory.tsx
frontend/src/features/directory/components/FilterableVendorTable.tsx
frontend/src/features/directory/components/VendorCard.tsx
frontend/src/features/directory/components/filters/FilterContext.ts
frontend/src/features/directory/components/filters/ServiceFilter.tsx
frontend/src/features/directory/components/tableLayout/FilterSection.tsx
frontend/src/features/directory/components/tableLayout/ResultsHeader.tsx
frontend/src/features/directory/hooks/useAnalyticsTracking.ts
frontend/src/features/directory/hooks/useVendorFiltering.ts
frontend/src/lib/constants.ts
frontend/src/lib/directory/filterTags.ts
frontend/src/utils/analytics/trackFilterEvents.ts

* Separate services and skills
* Add another filter for services (Hair and Makeup)
* Standardize chips for filters
* Add pills for removing filters to the top of the directory

Separate service and skill tags

---

frontend/src/features/directory/components/VendorCard.tsx
frontend/src/features/directory/components/tableLayout/ResultsHeader.tsx

* add service metric to card clicks
* disable removable filter pills when table is loading

add service metric to card clicks

---

frontend/next.config.ts
frontend/src/components/ui/FilterChip.tsx
frontend/src/features/directory/components/VendorCard.tsx
frontend/src/features/directory/components/VendorCardImage.tsx

* Use Next.js Image Optimization to handle sizing and caching in edge network.
* Supabase is still the source of truth

use next image optimization for vendor cards

---

frontend/src/features/business/components/VendorDetails.tsx
frontend/src/features/directory/components/VendorCard.tsx
frontend/src/features/directory/components/VendorCardImage.tsx

Applies the Next.js Image optimization of #104 to basic profile pages

use next.js image optimization on basic profile listings

---

frontend/package.json
frontend/src/features/contact/api/airtable.ts
frontend/src/features/contact/components/LeadCaptureForm.tsx
frontend/src/lib/airtable/constants.ts
frontend/src/utils/analytics/trackFormEvents.ts

* push metrics to data layer
* use library for airtable api call
* collect partial leads with airtable

add metrics to contact form
